const fs = require('fs');
const path = require('path');
const https = require('https');
const http = require('http');

const root = path.join(__dirname, '..');
const categoriesDir = path.join(root, 'src/data/catalog/categories');
const cachePath = path.join(root, 'src/data/catalog/url_verification_cache.json');

const sourceUrls = {
  'chatgpt': 'https://chatgpt.com',
  'claude': 'https://claude.ai',
  'gemini': 'https://gemini.google.com',
  'perplexity-ai': 'https://www.perplexity.ai',
  'deepseek-chat': 'https://chat.deepseek.com',
  'le-chat-mistral': 'https://chat.mistral.ai',
  'poe': 'https://poe.com',
  'huggingchat': 'https://huggingface.co/chat',
  'phind': 'https://www.phind.com',
  'duckduckgo-ai-chat': 'https://duckduckgo.com/chat',
  'jan-ai': 'https://jan.ai',
  'cursor-ai': 'https://www.cursor.com',
  'windsurf-ai': 'https://codeium.com/windsurf',
  'codeium': 'https://codeium.com',
  'amazon-q': 'https://aws.amazon.com/q/',
  'crewai': 'https://www.crewai.com',
  'devin': 'https://devin.ai',
  'notebooklm': 'https://notebooklm.google.com',
  'raycast-ai': 'https://www.raycast.com/ai',
  'craft-ai': 'https://www.craft.do/ai',
  'reflect-ai': 'https://reflect.app',
  'supernormal': 'https://supernormal.com',
  'fathom-ai': 'https://fathom.video',
  'avoma': 'https://www.avoma.com',
  'bardeen-ai': 'https://www.bardeen.ai',
  'relevance-ai': 'https://relevanceai.com',
  'flowise': 'https://flowiseai.com',
  'langflow': 'https://www.langflow.org',
  'dify-ai': 'https://dify.ai',
  'chatbase': 'https://www.chatbase.co',
  'voiceflow': 'https://www.voiceflow.com',
  'botpress': 'https://botpress.com',
  'intercom-fin-ai': 'https://www.intercom.com/fin',
  'salesforce-einstein': 'https://www.salesforce.com/einstein/',
  'hubspot-breeze': 'https://www.hubspot.com/products/artificial-intelligence',
  'cohere-rerank': 'https://cohere.com/rerank',
  'fireworks-ai': 'https://fireworks.ai',
  'groq': 'https://groq.com',
  'together-ai': 'https://www.together.ai',
  'replicate': 'https://replicate.com',
  'openrouter': 'https://openrouter.ai',
  'langgraph': 'https://langchain-ai.github.io/langgraph/',
  'sglang-engine': 'https://github.com/sgl-project/sglang',
  'tensorrt-llm': 'https://github.com/NVIDIA/TensorRT-LLM',
  'deepspeed-fastgen': 'https://github.com/microsoft/DeepSpeed',
  'outlines-framework': 'https://github.com/dottxt-ai/outlines',
  'guidance-framework': 'https://github.com/guidance-ai/guidance',
  'claude-code-cli': 'https://docs.anthropic.com/en/docs/claude-code',
  'midjourney': 'https://www.midjourney.com',
  'stable-diffusion': 'https://stability.ai',
  'dall-e-3': 'https://openai.com/index/dall-e-3/',
  'flux-1': 'https://blackforestlabs.ai',
  'leonardo-ai': 'https://leonardo.ai',
  'playground-ai': 'https://playground.com',
  'ideogram': 'https://ideogram.ai',
  'clipdrop-image': 'https://clipdrop.co',
  'recraft': 'https://www.recraft.ai',
  'seaart-ai': 'https://www.seaart.ai',
  'krea-ai': 'https://www.krea.ai',
  'craiyon': 'https://www.craiyon.com',
  'tensor-art': 'https://tensor.art',
  'civitai': 'https://civitai.com',
  'adobe-firefly': 'https://firefly.adobe.com',
  'canva-text-to-image': 'https://www.canva.com/ai-image-generator/',
  'nightcafe': 'https://creator.nightcafe.studio',
  'artbreeder': 'https://www.artbreeder.com',
  'deepai-image': 'https://deepai.org',
  'picsart-ai-studio': 'https://picsart.com/ai-image-generator',
  'microsoft-designer': 'https://designer.microsoft.com',
  'visual-electric': 'https://visualelectric.com',
  'magnific-ai': 'https://magnific.ai',
  'freepik-ai': 'https://www.freepik.com/ai',
  'lexica-art': 'https://lexica.art',
  'bluewillow': 'https://www.bluewillow.ai',
  'starryai': 'https://starryai.com',
  'dreamstudio': 'https://dreamstudio.ai',
  'wombo-dream': 'https://dream.ai',
  'openart-ai': 'https://openart.ai',
  'scenario-gg': 'https://www.scenario.com',
  'runway-canvas': 'https://runwayml.com',
  'storydiffusion': 'https://github.com/HVision-NKU/StoryDiffusion',
  'fooocus': 'https://github.com/lllyasviel/Fooocus',
  'comfyui': 'https://github.com/comfyanonymous/ComfyUI',
  'automatic1111': 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
  'diffusionbee': 'https://diffusionbee.com',
  'novelai': 'https://novelai.net',
  'controlnet-sd': 'https://github.com/lllyasviel/ControlNet',
  'ip-adapter': 'https://github.com/tencent-ailab/IP-Adapter',
  'sdxl-turbo': 'https://huggingface.co/stabilityai/sdxl-turbo',
  'flux-1-schnell': 'https://huggingface.co/black-forest-labs/FLUX.1-schnell',
  'kolors-ai': 'https://github.com/Kwai-Kolors/Kolors',
  'pixart-alpha': 'https://github.com/PixArt-alpha/PixArt-alpha',
  'diffusers-huggingface': 'https://github.com/huggingface/diffusers',
  'runway-gen-3-alpha': 'https://runwayml.com',
  'luma-dream-machine': 'https://lumalabs.ai/dream-machine',
  'openai-sora': 'https://openai.com/sora',
  'pika-labs': 'https://pika.art',
  'kling-ai': 'https://klingai.com',
  'haiper-ai': 'https://haiper.ai',
  'elai-io': 'https://elai.io',
  'kaiber': 'https://www.kaiber.ai',
  'deepbrain-ai': 'https://www.deepbrain.io',
  'colossyan': 'https://www.colossyan.com',
  'd-id': 'https://www.d-id.com',
  'hedra-ai': 'https://www.hedra.com',
  'viggle-ai': 'https://viggle.ai',
  'pixverse': 'https://pixverse.ai',
  'vidu-ai': 'https://www.vidu.com',
  'minimax-video': 'https://hailuoai.video',
  'domoai': 'https://www.domoai.app',
  'topaz-video-ai': 'https://www.topazlabs.com/topaz-video-ai',
  'fliki-video': 'https://fliki.ai',
  'tavus': 'https://www.tavus.io',
  'rephrase-ai': 'https://www.rephrase.ai',
  'munch-ai': 'https://www.getmunch.com',
  'vizard-ai': 'https://vizard.ai',
  'klap-ai': 'https://klap.app',
  'pictory-ai': 'https://pictory.ai',
  'lumen5': 'https://lumen5.com',
  'kapwing-video-ai': 'https://www.kapwing.com/ai',
  'rask-ai': 'https://www.rask.ai',
  'elevenlabs': 'https://elevenlabs.io',
  'suno-ai': 'https://suno.com',
  'udio': 'https://www.udio.com',
  'resemble-ai': 'https://www.resemble.ai',
  'play-ht': 'https://play.ht',
  'murf-ai': 'https://murf.ai',
  'speechify-voice': 'https://speechify.com',
  'cleanvoice': 'https://cleanvoice.ai',
  'lovo-ai': 'https://lovo.ai',
  'revoice-ai': 'https://www.revoice.com',
  'voicemod-ai': 'https://www.voicemod.net',
  'replica-studios': 'https://replicastudios.com',
  'wellsaid-labs': 'https://wellsaidlabs.com',
  'respeecher': 'https://www.respeecher.com',
  'altered-ai': 'https://www.altered.ai',
  'voice-ai': 'https://voice.ai',
  'fish-speech': 'https://github.com/fishaudio/fish-speech',
  'cosyvoice': 'https://github.com/FunAudioLLM/CosyVoice',
  'tortoise-tts': 'https://github.com/neonbjb/tortoise-tts',
  'piper-tts': 'https://github.com/rhasspy/piper',
  'vits-voice': 'https://github.com/jaywalnut310/vits',
  'aiva': 'https://www.aiva.ai',
  'beatoven-ai': 'https://www.beatoven.ai',
  'boomy': 'https://boomy.com',
  'mubert': 'https://mubert.com',
  'loudly': 'https://www.loudly.com',
  'soundraw-music': 'https://soundraw.io',
  'stable-audio-2-0': 'https://www Stability.ai',
  'riffusion': 'https://www.riffusion.com',
  'musiclm': 'https://musiclm.com',
  'musicfy-ai': 'https://musicfy.lol',
  'lalal-ai': 'https://www.lalal.ai',
  'moises-ai': 'https://moises.ai',
  'kits-ai': 'https://www.kits.ai',
  'vocalremover-org': 'https://vocalremover.org',
  'landr-ai-mastering': 'https://www.landr.com',
  'izotope-ozone-11': 'https://www.izotope.com/en/products/ozone.html',
  'emastered': 'https://emastered.com',
  'auphonic': 'https://auphonic.com',
  'podcastle-ai': 'https://podcastle.ai',
  'audacity-openvino': 'https://www.audacityteam.org',
  'consensus-ai': 'https://consensus.app',
  'elicit-com': 'https://elicit.com',
  'scite-ai': 'https://scite.ai',
  'connected-papers': 'https://www.connectedpapers.com',
  'scispace-typeset': 'https://typeset.io',
  'semantic-scholar': 'https://www.semanticscholar.org',
  'researchrabbit': 'https://www.researchrabbit.ai',
  'scholarcy': 'https://www.scholarcy.com',
  'humata-ai': 'https://www.humata.ai',
  'explainpaper': 'https://www.explainpaper.com',
  'genei-io': 'https://www.genei.io',
  'kimi-ai': 'https://www.kimi.com',
  'genspark-search': 'https://www.genspark.ai',
  'andi-search': 'https://andisearch.com',
  'exa-ai-metaphor': 'https://exa.ai',
  'brave-leo-search': 'https://brave.com/leo/',
  'komo-ai': 'https://komo.ai',
  'paperpal': 'https://paperpal.com',
  'writefull': 'https://www.writefull.com',
  'iris-ai': 'https://iris.ai',
  'rayyan-ai': 'https://www.rayyan.ai',
  'litmaps': 'https://www.litmaps.co',
  'papers-digest': 'https://www.paperdigest.org',
  'openread': 'https://www.openread.academy',
  'inciteful': 'https://inciteful.xyz',
  'openalex-ai': 'https://openalex.org',
  'arxiv-sanity': 'https://arxiv-sanity-lite.com',
  'scirate-ai': 'https://scirate.com',
  'overleaf-ai': 'https://www.overleaf.com',
  'jenni-ai': 'https://jenni.ai',
  'arxiv-sanitary': 'https://arxiv.org',
  'grammarly-ai': 'https://www.grammarly.com',
  'copy-ai': 'https://www.copy.ai',
  'jasper-ai': 'https://www.jasper.ai',
  'writesonic': 'https://writesonic.com',
  'rytr': 'https://rytr.me',
  'quillbot': 'https://quillbot.com',
  'sudowrite': 'https://sudowrite.com',
  'wordtune': 'https://www.wordtune.com',
  'hyperwrite': 'https://www.hyperwriteai.com',
  'lex-page': 'https://lex.page',
  'anyword': 'https://anyword.com',
  'prowritingaid': 'https://prowritingaid.com',
  'languagetool-ai': 'https://languagetool.org',
  'contentscale': 'https://contentscale.ai',
  'surfer-seo-ai': 'https://surferseo.com',
  'frase-io': 'https://www.frase.io',
  'marketmuse': 'https://www.marketmuse.com',
  'textcortex': 'https://textcortex.com',
  'paragraphai': 'https://paragraphai.com',
  'simplified-writing': 'https://simplified.com',
  'copysmith': 'https://copysmith.ai',
  'peppertype-ai': 'https://www.peppertype.ai',
  'hypotenuse-ai': 'https://www.hypotenuse.ai',
  'longshot-ai': 'https://longshot.ai',
  'hoppycopy': 'https://www.hoppycopy.co',
  'writer-com': 'https://writer.com',
  'seo-wind': 'https://seowind.io',
  'openai-canvas': 'https://openai.com/index/introducing-canvas/',
  'magic-school-ai': 'https://www.magicschool.ai',
  'quizizz-ai': 'https://quizizz.com',
  'khanmigo': 'https://www.khanacademy.org/khanmigo',
  'diffit': 'https://beta.diffit.me',
  'brisk-teaching': 'https://www.briskteaching.com',
  'eduaide-ai': 'https://www.eduaide.ai',
  'teachable-machine': 'https://teachablemachine.withgoogle.com',
  'curipod': 'https://curipod.com',
  'monic-ai': 'https://monic.ai',
  'gradescope-ai': 'https://www.gradescope.com',
  'classpoint-ai': 'https://www.classpoint.io',
  'schoolai': 'https://schoolai.com',
  'goblin-tools': 'https://goblin.tools',
  'questionwell': 'https://questionwell.org',
  'kahoot-ai': 'https://kahoot.com',
  'quizlet-q-chat': 'https://quizlet.com',
  'duolingo-max': 'https://www.duolingo.com',
  'quizgecko': 'https://quizgecko.com',
  'formative-ai': 'https://www.formative.com',
  'edpuzzle-ai': 'https://edpuzzle.com',
  'nearpod-ai': 'https://nearpod.com',
  'photomath': 'https://photomath.com',
  'symbolab-ai': 'https://www.symbolab.com',
  'wolfram-alpha-ai': 'https://www.wolframalpha.com',
  'mathway-ai': 'https://www.mathway.com',
  'microsoft-math-solver': 'https://mathsolver.microsoft.com',
  'gauthmath': 'https://gauthmath.com',
  'socratic-by-google': 'https://socratic.org',
  'brainly-ai': 'https://brainly.com',
  'elsa-speak': 'https://elsaspeak.com',
  'speechace': 'https://speechace.com',
  'talkpal-ai': 'https://talkpal.ai',
  'memrise-ai': 'https://www.memrise.com',
  'busuu-ai': 'https://www.busuu.com',
  'hellotalk-ai': 'https://www.hellotalk.com',
  'turnitin-ai-detector': 'https://www.turnitin.com',
  'gptzero': 'https://gptzero.me',
  'originality-ai': 'https://originality.ai',
  'copyleaks-ai-detector': 'https://copyleaks.com',
  'whisper-openai': 'https://github.com/openai/whisper',
  'otter-ai': 'https://otter.ai',
  'fireflies-ai': 'https://fireflies.ai',
  'notta-ai': 'https://www.notta.ai',
  'fathom-video': 'https://fathom.video',
  'meetgeek-ai': 'https://meetgeek.ai',
  'sonix-ai': 'https://sonix.ai',
  'rev-ai': 'https://www.rev.ai',
  'gladia-io': 'https://www.gladia.io',
  'assemblyai': 'https://www.assemblyai.com',
  'riverside-transcribe': 'https://riverside.fm',
  'tactiq-io': 'https://tactiq.io',
  'macwhisper': 'https://goodsnooze.gumroad.com/l/macwhisper',
  'trint-ai': 'https://trint.com',
  'happy-scribe': 'https://www.happyscribe.com',
  'speechmatics': 'https://www.speechmatics.com',
  'vosk-ai-transcribe': 'https://alphacephei.com/vosk/',
  'whisper-cpp': 'https://github.com/ggerganov/whisper.cpp',
  'whisperx': 'https://github.com/m-bain/whisperX',
  'faster-whisper': 'https://github.com/SYSTRAN/faster-whisper',
  'buzz-whisper': 'https://github.com/chidiwilliams/buzz',
  'sensevoice': 'https://github.com/FunAudioLLM/SenseVoice',
  'funasr': 'https://github.com/modelscope/FunASR',
  'speechbrain': 'https://speechbrain.github.io',
  'deep-speech-mozilla': 'https://github.com/mozilla/DeepSpeech',
  'wav2vec-2-0': 'https://huggingface.co/docs/transformers/model_doc/wav2vec2',
  'photoroom': 'https://www.photoroom.com',
  'clipdrop-edit': 'https://clipdrop.co',
  'remove-bg': 'https://www.remove.bg',
  'canva-magic-studio': 'https://www.canva.com/magic-studio/',
  'photoshop-firefly-fill': 'https://www.adobe.com/products/photoshop/generative-fill.html',
  'vanceai-photo': 'https://vanceai.com',
  'cutout-pro-photo': 'https://www.cutout.pro',
  'pixelcut-photo': 'https://www.pixelcut.ai',
  'upscayl-photo': 'https://upscayl.org',
  'topaz-gigapixel-ai': 'https://www.topazlabs.com/gigapixel',
  'lets-enhance': 'https://letsenhance.io',
  'luminar-neo': 'https://skylum.com/luminar',
  'evoto-ai-photo': 'https://www.evoto.ai',
  'befunky-photo-ai': 'https://www.befunky.com',
  'fotor-photo-ai': 'https://www.fotor.com',
  'picsart-photo-ai': 'https://picsart.com',
  'adobe-express-photo': 'https://www.adobe.com/express/',
  'pixlr-photo-ai': 'https://pixlr.com',
  'deepimage-photo-ai': 'https://deep-image.ai',
  'hitpaw-photo-ai': 'https://www.hitpaw.com',
  'avclabs-photo-ai': 'https://www.avclabs.com/photo-ai.html',
  'inpaint-anything': 'https://github.com/geekyutao/Inpaint-Anything',
  'segment-anything-2-sam-2': 'https://ai.meta.com/sam2/',
  'grounded-sam': 'https://github.com/IDEA-Research/Grounded-SAM-2',
  'draggan': 'https://github.com/ZhengyiYu/DragGAN',
  'dragdiffusion': 'https://github.com/Yujun-Shi/DragDiffusion',
  'brushnet-ai': 'https://github.com/nullxploitation/BrushNet',
  'paint-by-example': 'https://github.com/Fantasy-Studio/Paint-by-Example',
  'napkin-ai': 'https://www.napkin.ai',
  'gamma-app': 'https://gamma.app',
  'tome-app': 'https://tome.app',
  'beautiful-ai': 'https://www.beautiful.ai',
  'pitch-ai': 'https://pitch.com',
  'slidesgpt': 'https://slidesgpt.com',
  'decktopus': 'https://www.decktopus.com',
  'prezi-ai': 'https://prezi.com/ai/',
  'slidesai-io': 'https://www.slidesai.io',
  'canva-slides-ai': 'https://www.canva.com/create/presentations/',
  'plus-ai-google-slides': 'https://plusai.com',
  'magicslides-app': 'https://www.magicslides.app',
  'slidebean': 'https://slidebean.com',
  'visme-ai-presentations': 'https://www.visme.co/ai-presentation-maker/',
  'piktochart-decks': 'https://piktochart.com',
  'venngage-presentation': 'https://venngage.com',
  'powerpoint-copilot': 'https://www.microsoft.com/microsoft-365/powerpoint',
  'google-slides-gemini': 'https://workspace.google.com/intl/en_in/products/slides/',
  'mentimeter-ai': 'https://www.mentimeter.com',
  'genially-presentations': 'https://genially.com',
  'emaze-ai': 'https://www.emaze.com',
  'haiku-deck-ai': 'https://www.haikudeck.com',
  'mesh y-ai': 'https://www.meshy.ai',
  'meshy-ai': 'https://www.meshy.ai',
  'tripo3d': 'https://www.tripo3d.ai',
  'csm-3d': 'https://www.csm.ai',
  'spline-ai': 'https://spline.design',
  'luma-genie-3d': 'https://lumalabs.ai/genie',
  'inworld-ai': 'https://inworld.ai',
  'layer-ai': 'https://www.layer.ai',
  'rosebud-ai': 'https://www.rosebud.ai',
  'masterpiece-x': 'https://www.masterpiecex.com',
  'polycam-3d-ai': 'https://poly.cam',
  'blockade-labs-skybox': 'https://skybox.blockadelabs.com',
  'plask-ai': 'https://plask.ai',
  'sloyd-ai': 'https://www.sloyd.ai',
  'kaedim-3d': 'https://www.kaedim3d.com',
  'meshcapade': 'https://meshcapade.com',
  'alpha3d': 'https://www.alpha3d.io',
  'deepmotion-ai': 'https://www.deepmotion.com',
  'cascadeur-ai': 'https://cascadeur.com',
  'wonder-dynamics': 'https://wonderdynamics.com',
  'nvidia-audio2face': 'https://www.nvidia.com/en-us/omniverse/apps/audio2face/',
  'convai-dev': 'https://convai.com',
  'charisma-ai': 'https://charisma.ai',
  'unity-muse': 'https://unity.com/products/muse',
  'roblox-ai-assistant': 'https://create.roblox.com/docs/assistant',
  'blender-dream-texture': 'https://github.com/carson-katri/dream-textures',
  'substance-3d-ai': 'https://www.adobe.com/products/substance3d/apps/painter.html',
  'nerf-studio': 'https://docs.nerf.studio',
  'instant-ngp': 'https://github.com/NVlabs/instant-ngp',
  'kiri-engine': 'https://www.kiriengine.app',
  'realitycapture-ai': 'https://www.capturingreality.com',
  'meshroom-ai': 'https://alicevision.org/#meshroom',
  'promethean-ai': 'https://www.prometheanai.com',
  'ai-dungeon-2': 'https://aidungeon.com',
  'novelai-storyteller': 'https://novelai.net',
  '3d-gaussian-splatting': 'https://repo-sam.inria.fr/funkers/3d-gaussian-splatting/',
  'supersplat-3d': 'https://superspl.at',
  'open3d-ai': 'https://www.open3d.org',
  'dreamgaussian': 'https://github.com/dreamgaussian/dreamgaussian',
  'text2mesh': 'https://github.com/threedle/text2mesh',
  'controlnet3d': 'https://github.com/YouDream3D/ControlNet3D'
};

function check(url) {
  return new Promise(resolve => {
    let parsed;
    try { parsed = new URL(url); } catch { resolve('rejected'); return; }
    const client = parsed.protocol === 'https:' ? https : http;
    const request = client.request(url, { method: 'HEAD', headers: { 'User-Agent': 'Mozilla/5.0' }, timeout: 2500 }, response => {
      if (response.statusCode >= 200 && response.statusCode < 400) resolve('verified');
      else if (response.statusCode === 401 || response.statusCode === 403 || response.statusCode === 429) resolve('bot_blocked');
      else resolve('rejected');
      response.resume();
    });
    request.on('timeout', () => { request.destroy(); resolve('rejected'); });
    request.on('error', () => resolve('rejected'));
    request.end();
  });
}

function loadCategory(file) {
  const source = fs.readFileSync(file, 'utf8');
  const match = source.match(/export const (\w+): AITool\[\] = ([\s\S]*);\s*$/);
  if (!match) throw new Error(`Could not parse ${file}`);
  const tools = Function(`return (${match[2]})`)();
  return { exportName: match[1], tools };
}

async function main() {
  const cache = JSON.parse(fs.readFileSync(cachePath, 'utf8'));
  const uncachedUrls = [...new Set(Object.values(sourceUrls))].filter(url => !cache[url]);
  const statuses = await Promise.all(uncachedUrls.map(async url => [url, await check(url)]));
  for (const [url, status] of statuses) cache[url] = status;
  let changed = 0;
  let matched = 0;
  for (const fileName of fs.readdirSync(categoriesDir).filter(file => file.endsWith('.ts'))) {
    if (fileName === 'focused_tools.ts' || fileName === 'website_app_creation.ts') continue;
    const filePath = path.join(categoriesDir, fileName);
    const { exportName, tools } = loadCategory(filePath);
    for (const tool of tools) {
      const url = sourceUrls[tool.slug];
      if (!url) continue;
      matched++;
      const status = cache[url];
      if (status === 'verified' || status === 'bot_blocked') {
        if (tool.officialUrl !== url || tool.officialStatus !== 'verified') changed++;
        tool.officialUrl = url;
        tool.officialStatus = 'verified';
        tool.verifiedAt = new Date().toISOString().slice(0, 10);
      }
    }
    const content = `import { AITool } from '../../../types/tool';\n\nexport const ${exportName}: AITool[] = ${JSON.stringify(tools, null, 2)};\n`;
    fs.writeFileSync(filePath, content);
  }
  fs.writeFileSync(cachePath, JSON.stringify(cache, null, 2) + '\n');
  console.log(`Matched ${matched} source-backed records and promoted ${changed}; cache now contains ${Object.keys(cache).length} URLs.`);
}

main().catch(error => { console.error(error); process.exit(1); });